from __future__ import annotations
import os, json
from io import BytesIO
from datetime import datetime
from reportlab.lib.pagesizes import A4
from reportlab.pdfgen import canvas
from reportlab.lib.units import mm

DISCLAIMER = (
    "This report is generated by a rules-based tool and may rely on user-supplied library data. "
    "It is not a substitute for professional engineering judgement. "
    "Users must verify inputs, standards, substrates, fixings, fire strategy, dynamic/seismic requirements, "
    "corrosion environment and suitability for the project."
)

def build_pdf(project_name: str, bracket_reference: str, snapshot: dict, result: dict, tool_version: str, library_version: str="user-supplied") -> bytes:
    buf = BytesIO()
    c = canvas.Canvas(buf, pagesize=A4)
    w, h = A4

    c.setFont("Helvetica-Bold", 14)
    c.drawString(20*mm, h-20*mm, "MEP Trapeze Bracket Design Record")
    c.setFont("Helvetica", 10)
    c.drawString(20*mm, h-27*mm, f"Project: {project_name}")
    c.drawString(20*mm, h-33*mm, f"Bracket Reference: {bracket_reference}")
    c.drawString(20*mm, h-39*mm, f"Generated: {datetime.utcnow().isoformat()}Z")
    c.drawString(20*mm, h-45*mm, f"Tool Version: {tool_version}  |  Library: {library_version}")

    c.setFont("Helvetica-Bold", 12)
    c.drawString(20*mm, h-60*mm, "Result Summary")
    c.setFont("Helvetica", 10)
    c.drawString(20*mm, h-67*mm, f"Overall Status: {result.get('status')}  |  Governing: {result.get('governing_check')}")
    c.drawString(20*mm, h-73*mm, f"Total Weight: {result.get('total_weight_kg')} kg  |  Rod Minimum: {result.get('rod_min_size')}")

    y = h-85*mm
    c.setFont("Helvetica-Bold", 10)
    c.drawString(20*mm, y, "Checks")
    y -= 6*mm
    c.setFont("Helvetica", 10)
    for k, v in (result.get("checks") or {}).items():
        c.drawString(25*mm, y, f"{k}: {v}")
        y -= 5*mm

    y -= 6*mm
    c.setFont("Helvetica-Bold", 10)
    c.drawString(20*mm, y, "Per-tier")
    y -= 6*mm
    c.setFont("Helvetica", 10)
    per = result.get("per_tier_weight_kg") or {}
    for tier in sorted(per.keys(), key=lambda x: int(x)):
        c.drawString(25*mm, y, f"Tier {tier}: {per[tier]} kg, defl {result.get('deflection_mm',{}).get(int(tier))} mm, "
                              f"M {result.get('max_moment_knm',{}).get(int(tier))} kNm")
        y -= 5*mm

    y -= 8*mm
    c.setFont("Helvetica-Bold", 10)
    c.drawString(20*mm, y, "Inputs Snapshot (JSON)")
    y -= 6*mm
    c.setFont("Helvetica", 7)
    snap_text = json.dumps(snapshot, indent=2)[:3000]
    for line in snap_text.splitlines()[:55]:
        c.drawString(20*mm, y, line[:120])
        y -= 3.2*mm
        if y < 25*mm:
            c.showPage()
            y = h-20*mm
            c.setFont("Helvetica", 7)

    if y < 45*mm:
        c.showPage()
        y = h-20*mm

    c.setFont("Helvetica-Oblique", 8)
    c.drawString(20*mm, 18*mm, DISCLAIMER)

    c.showPage()
    c.save()
    return buf.getvalue()
